"""add_indexes_and_ingestion_errors

Revision ID: 131b8e8f274a
Revises:
Create Date: 2026-03-17 00:33:37.778606

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "131b8e8f274a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Base Tables
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("broker", sa.String(), nullable=True),
        sa.Column("account_type", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("balance", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("free_margin", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("total_deposits", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "total_withdrawals", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("initial_balance", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("live", sa.Boolean(), nullable=True),
        sa.Column("real_account", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "strategies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("timeframe", sa.String(), nullable=True),
        sa.Column("operational_style", sa.String(), nullable=True),
        sa.Column("trade_duration", sa.String(), nullable=True),
        sa.Column("initial_balance", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("base_currency", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("live", sa.Boolean(), nullable=True),
        sa.Column("real_account", sa.Boolean(), nullable=True),
        sa.Column("account_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "portfolio_strategy",
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"]),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"]),
        sa.PrimaryKeyConstraint("portfolio_id", "strategy_id"),
    )

    # Note: Using sa.Enum explicitly to create the type in Postgres
    op.create_table(
        "deals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticket", sa.BigInteger(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column(
            "type", sa.Enum("BUY", "SELL", "BALANCE", name="dealtype"), nullable=False
        ),
        sa.Column("volume", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("profit", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("commission", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("swap", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"]),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        sa.UniqueConstraint(
            "ticket", "strategy_id", "timestamp", name="uq_deal_ticket_strategy"
        ),
    )

    op.create_table(
        "equity_curve",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("equity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"]),
        sa.PrimaryKeyConstraint("timestamp", "strategy_id"),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("topic", sa.String(length=32), nullable=True),
        sa.Column("raw_message", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_deals_strategy_timestamp",
        "deals",
        ["strategy_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_equity_strategy_timestamp",
        "equity_curve",
        ["strategy_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_equity_strategy_timestamp", table_name="equity_curve")
    op.drop_index("ix_deals_strategy_timestamp", table_name="deals")
    op.drop_table("ingestion_errors")
    # ### end Alembic commands ###
