"""modernize_sqlalchemy_models

Revision ID: 550ad93f913d
Revises: b2c3d4e5f6a1
Create Date: 2026-03-20 21:56:52.903362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "550ad93f913d"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("deals_timestamp_idx", table_name="deals")
    op.drop_index("equity_curve_timestamp_idx", table_name="equity_curve")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "equity_curve_timestamp_idx",
        "equity_curve",
        [sa.text("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "deals_timestamp_idx", "deals", [sa.text("timestamp DESC")], unique=False
    )
    # ### end Alembic commands ###
