"""float_to_numeric_financial_fields

Revision ID: b794a8071944
Revises: dbf05a2a2df4
Create Date: 2026-03-17 11:28:13.064211

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b794a8071944"
down_revision: str | None = "dbf05a2a2df4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "free_margin",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "total_deposits",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "total_withdrawals",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "volume",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "profit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "commission",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "swap",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_equity",
        "balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_equity",
        "equity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "backtests",
        "initial_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "volume",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "profit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "commission",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "swap",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "equity_curve",
        "balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "equity_curve",
        "equity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "portfolios",
        "initial_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "strategies",
        "initial_balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=18, scale=8),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "strategies",
        "initial_balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "portfolios",
        "initial_balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "equity_curve",
        "equity",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "equity_curve",
        "balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "swap",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "commission",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "profit",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "price",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "deals",
        "volume",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtests",
        "initial_balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_equity",
        "equity",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_equity",
        "balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "swap",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "commission",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "profit",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "price",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "volume",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "total_withdrawals",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "total_deposits",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "free_margin",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "accounts",
        "balance",
        existing_type=sa.Numeric(precision=18, scale=8),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
