"""add_backtest_tables

Revision ID: dbf05a2a2df4
Revises: 131b8e8f274a
Create Date: 2026-03-17 10:07:59.959151

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbf05a2a2df4"
down_revision: str | None = "131b8e8f274a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("client_run_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("timeframe", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("initial_balance", sa.Float(), nullable=True),
        sa.Column("parameters", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "strategy_id", "client_run_id", name="_backtest_strategy_run_uc"
        ),
    )
    op.create_table(
        "backtest_deals",
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ticket", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column(
            "type",
            postgresql.ENUM(
                "BUY", "SELL", "BALANCE", name="dealtype", create_type=False
            ),
            nullable=True,
        ),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("profit", sa.Float(), nullable=True),
        sa.Column("commission", sa.Float(), nullable=True),
        sa.Column("swap", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
        ),
        sa.PrimaryKeyConstraint("backtest_id", "timestamp", "ticket"),
    )
    op.create_index(
        "ix_backtest_deals_id_ts",
        "backtest_deals",
        ["backtest_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "backtest_equity",
        sa.Column("backtest_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("equity", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["backtest_id"],
            ["backtests.id"],
        ),
        sa.PrimaryKeyConstraint("backtest_id", "timestamp"),
    )
    op.create_index(
        "ix_backtest_equity_id_ts",
        "backtest_equity",
        ["backtest_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_backtest_equity_id_ts", table_name="backtest_equity")
    op.drop_table("backtest_equity")
    op.drop_index("ix_backtest_deals_id_ts", table_name="backtest_deals")
    op.drop_table("backtest_deals")
    op.drop_table("backtests")
    # ### end Alembic commands ###
