"""nullable_false_required_fields

Revision ID: 4bddbcefddce
Revises: b794a8071944
Create Date: 2026-03-17 11:43:51.256485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4bddbcefddce"
down_revision: str | None = "b794a8071944"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backtest_deals", "symbol", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "backtest_deals",
        "type",
        existing_type=postgresql.ENUM("BUY", "SELL", "BALANCE", name="dealtype"),
        nullable=False,
    )
    op.alter_column(
        "backtest_deals",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_deals",
        "price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_deals",
        "profit",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_deals",
        "commission",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_deals",
        "swap",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_equity",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "backtest_equity",
        "equity",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column("deals", "symbol", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "deals",
        "type",
        existing_type=postgresql.ENUM("BUY", "SELL", "BALANCE", name="dealtype"),
        nullable=False,
    )
    op.alter_column(
        "deals",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "deals",
        "price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "deals",
        "profit",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "deals",
        "commission",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "deals", "swap", existing_type=sa.NUMERIC(precision=18, scale=8), nullable=False
    )
    op.alter_column(
        "equity_curve",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    op.alter_column(
        "equity_curve",
        "equity",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "equity_curve",
        "equity",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "equity_curve",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "deals", "swap", existing_type=sa.NUMERIC(precision=18, scale=8), nullable=True
    )
    op.alter_column(
        "deals",
        "commission",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "deals",
        "profit",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "deals", "price", existing_type=sa.NUMERIC(precision=18, scale=8), nullable=True
    )
    op.alter_column(
        "deals",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "deals",
        "type",
        existing_type=postgresql.ENUM("BUY", "SELL", "BALANCE", name="dealtype"),
        nullable=True,
    )
    op.alter_column("deals", "symbol", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "backtest_equity",
        "equity",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_equity",
        "balance",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "swap",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "commission",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "profit",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "price",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "volume",
        existing_type=sa.NUMERIC(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals",
        "type",
        existing_type=postgresql.ENUM("BUY", "SELL", "BALANCE", name="dealtype"),
        nullable=True,
    )
    op.alter_column(
        "backtest_deals", "symbol", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
